import { NuvioAddon } from "@/types/nuvio";

export const RECOMMENDED_ADDONS: NuvioAddon[] = [
  {
    id: "aiostreams",
    name: "AIOStreams",
    description: "Agrégateur multi-sources universel ultra rapide avec support des debrid (Real-Debrid, AllDebrid, TorBox), filtrage de langues et résolutions.",
    category: "streaming",
    manifestUrl: "https://aiostreams.am/manifest.json",
    installUrl: "stremio://aiostreams.am/manifest.json",
    iconUrl: "https://aiostreams.am/logo.png",
    version: "2.4.0",
    isOfficial: false,
    tags: ["Debrid", "Multi-sources", "Recommandé FR", "4K/HDR"],
  },
  {
    id: "torrentio",
    name: "Torrentio RD / AD",
    description: "Le scraper torrent & débrid de référence mondial pour les flux films et séries, optimisé pour les fichiers multilingues / MULTI (VFF, VFQ).",
    category: "streaming",
    manifestUrl: "https://torrentio.strem.fun/manifest.json",
    installUrl: "stremio://torrentio.strem.fun/manifest.json",
    iconUrl: "https://torrentio.strem.fun/favicon.ico",
    version: "1.0.13",
    isOfficial: false,
    tags: ["Torrent", "Real-Debrid", "Incontournable"],
  },
  {
    id: "tmdb-addon",
    name: "The Movie Database (TMDB)",
    description: "Fournisseur de métadonnées officiel fournissant résumés en français, affiches localisées, notes TMDB et fiches de casting complètes. Installé automatiquement par le configurateur, sans clé API personnelle.",
    category: "metadata",
    manifestUrl: "https://94c8cb9f702d-tmdb-addon.baby-beamup.club/manifest.json",
    installUrl: "stremio://94c8cb9f702d-tmdb-addon.baby-beamup.club/manifest.json",
    iconUrl: "https://www.themoviedb.org/assets/2/v4/logos/v2/blue_square_2-d537fb228cf3ded904ef09b136fe3fec72548ebc1fea3fbbd1ad9e36364db38b.svg",
    version: "1.2.0",
    isOfficial: true,
    tags: ["Métadonnées", "FR", "Officiel", "Auto"],
  },
  {
    id: "lumio",
    name: "Lumio",
    description: "Addon francophone de recherche et de flux. Aucune clé API : le configurateur Nuvio installe le profil public Lumio automatiquement.",
    category: "streaming",
    manifestUrl: "https://mylumio.tv/manifest.json",
    installUrl: "stremio://mylumio.tv/manifest.json",
    iconUrl: "https://mylumio.tv/favicon.ico",
    version: "1.0.0",
    isOfficial: false,
    tags: ["FR", "Flux", "Auto"],
  },
  {
    id: "bingecat",
    name: "BingeCat",
    description: "Catalogues, recherche IA et recommandations pour Nuvio. Instance publique sans inscription ni clé API, intégrée par l'assistant Nuvio.",
    category: "catalogue",
    manifestUrl: "https://bingecat.strem.fun/manifest.json",
    installUrl: "stremio://bingecat.strem.fun/manifest.json",
    iconUrl: "https://bingecat.com/favicon.ico",
    version: "1.0.0",
    isOfficial: false,
    tags: ["IA", "Catalogues", "Auto"],
  },
  {
    id: "cyberflix",
    name: "Cyberflix Catalog",
    description: "Catalogue complet classant les films et séries par plateforme de streaming (Netflix, Disney+, Prime Video, Apple TV+, Canal+, etc.).",
    category: "catalogue",
    manifestUrl: "https://cyberflix.elfhosted.com/manifest.json",
    installUrl: "stremio://cyberflix.elfhosted.com/manifest.json",
    iconUrl: "https://cyberflix.elfhosted.com/favicon.ico",
    version: "1.5.2",
    isOfficial: false,
    tags: ["Catalogues", "Plateformes", "Streaming"],
  },
  {
    id: "opensubtitles-v3",
    name: "OpenSubtitles v3 (FR)",
    description: "Le moteur de sous-titres officiel OpenSubtitles v3 pour trouver tous les sous-titres français (VOSTFR, sous-titres sourds et malentendants).",
    category: "sous-titres",
    manifestUrl: "https://opensubtitles-v3.strem.io/manifest.json",
    installUrl: "stremio://opensubtitles-v3.strem.io/manifest.json",
    iconUrl: "https://www.opensubtitles.org/favicon.ico",
    version: "1.0.0",
    isOfficial: true,
    tags: ["Sous-titres", "FR / VOSTFR", "Officiel"],
  },
  {
    id: "subdl",
    name: "SubDL Subtitles",
    description: "Complément de sous-titres très performant, idéal lorsque les sous-titres ne sont pas présents sur OpenSubtitles.",
    category: "sous-titres",
    manifestUrl: "https://subdl.strem.fun/manifest.json",
    installUrl: "stremio://subdl.strem.fun/manifest.json",
    iconUrl: "https://subdl.com/favicon.ico",
    version: "1.0.4",
    isOfficial: false,
    tags: ["Sous-titres", "Alternatif"],
  },
  {
    id: "anime-kitsu",
    name: "Anime Kitsu",
    description: "Catalogue d'animation japonaise complet avec synopsis en français, classement des saisons et intégration Kitsu.io.",
    category: "anime",
    manifestUrl: "https://anime-kitsu.strem.fun/manifest.json",
    installUrl: "stremio://anime-kitsu.strem.fun/manifest.json",
    iconUrl: "https://kitsu.io/favicon-32x32.png",
    version: "1.1.2",
    isOfficial: false,
    tags: ["Anime", "Manga", "Kitsu"],
  },
  {
    id: "mediafusion",
    name: "MediaFusion",
    description: "Scraper puissant pour les événements sportifs en direct, les replays et les flux internationaux.",
    category: "streaming",
    manifestUrl: "https://mediafusion.elfhosted.com/manifest.json",
    installUrl: "stremio://mediafusion.elfhosted.com/manifest.json",
    iconUrl: "https://mediafusion.elfhosted.com/favicon.ico",
    version: "3.2.0",
    isOfficial: false,
    tags: ["Sport", "Live", "International"],
  },
  {
    id: "rpdb-posters",
    name: "Rating Poster Database (RPDB)",
    description: "Ajoute les notes IMDb, Rotten Tomatoes et Metacritic directement sur les affiches de vos films et séries.",
    category: "metadata",
    manifestUrl: "https://rpdb.ratingposterdb.com/manifest.json",
    installUrl: "stremio://rpdb.ratingposterdb.com/manifest.json",
    iconUrl: "https://ratingposterdb.com/favicon.ico",
    version: "2.1.0",
    isOfficial: false,
    tags: ["Affiches", "Notes IMDb", "Rotten Tomatoes"],
  },
];
